apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-japan-deployment
  namespace: ostad
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-japan
  template:
    metadata:
      labels:
        app: next-japan
    spec:
      containers:
        - name: next-japan
          image: mrtoast07/next-japan:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
