apiVersion: v1
kind: Service
metadata:
  name: next-japan-service
  namespace: ostad
spec:
  type: NodePort
  selector:
    app: next-japan
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
